apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: petstore-upstream
  namespace: gloo-system
spec:
  kube:
    serviceName: default-petstore
    serviceNamespace: default
    servicePort: 8080
